# Generated by Django 5.2.12 on 2026-04-08 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(default='', max_length=20, verbose_name='Telefone'),
        ),
    ]
