# Generated by Django 5.2.13 on 2026-04-23 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='account',
        ),
    ]
