# Generated by Django 5.2.13 on 2026-04-16 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('subject', models.CharField(choices=[('login', 'Problemas de Login'), ('cadastro', 'Problemas de Cadastro'), ('trabalhos', 'Dúvidas sobre Trabalhos'), ('orcamentos', 'Dúvidas sobre Orçamentos'), ('planos', 'Dúvidas sobre Planos'), ('financeiro', 'Problemas Financeiros'), ('bug', 'Reportar Bug'), ('outro', 'Outro')], default='outro', max_length=30, verbose_name='Assunto')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lida')),
                ('response', models.TextField(blank=True, verbose_name='Resposta')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Respondido em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_responses', to=settings.AUTH_USER_MODEL, verbose_name='Respondido por')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_messages', to=settings.AUTH_USER_MODEL, verbose_name='Usuário (se logado)')),
            ],
            options={
                'verbose_name': 'Mensagem de Suporte',
                'verbose_name_plural': 'Mensagens de Suporte',
                'db_table': 'support_messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
