# Generated by Django 5.2.12 on 2026-04-03 03:46

import base.accounts.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('autonomous', 'Autônomo'), ('company', 'Empresa')], default='autonomous', max_length=20, verbose_name='Tipo de Conta')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('cnpj', models.CharField(blank=True, max_length=18, verbose_name='CNPJ')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Endereço')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='accounts/logos/', verbose_name='Logo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Bloqueada')),
                ('blocked_reason', models.TextField(blank=True, verbose_name='Motivo do Bloqueio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Conta',
                'verbose_name_plural': 'Contas',
                'db_table': 'accounts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True, verbose_name='Chave')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('is_premium', models.BooleanField(default=False, verbose_name='Premium')),
            ],
            options={
                'verbose_name': 'Funcionalidade',
                'verbose_name_plural': 'Funcionalidades',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='users/%Y/%m/', verbose_name='Foto')),
                ('role', models.CharField(blank=True, max_length=50, verbose_name='Função/Cargo')),
                ('is_account_admin', models.BooleanField(default=False, verbose_name='É Admin da Conta')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Bloqueado')),
                ('blocked_reason', models.TextField(blank=True, verbose_name='Motivo do Bloqueio')),
                ('blocked_at', models.DateTimeField(blank=True, null=True, verbose_name='Bloqueado em')),
                ('notes', models.TextField(blank=True, verbose_name='Anotações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='accounts.account', verbose_name='Conta')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', base.accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('tester', 'Teste'), ('basic', 'Básico'), ('business', 'Business')], max_length=20, unique=True, verbose_name='Tipo')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('max_users', models.PositiveIntegerField(default=1, verbose_name='Máximo de Usuários')),
                ('max_clients', models.PositiveIntegerField(default=10, verbose_name='Máximo de Clientes')),
                ('max_jobs', models.PositiveIntegerField(default=10, verbose_name='Máximo de Trabalhos')),
                ('max_expenses', models.PositiveIntegerField(default=10, verbose_name='Máximo de Despesas')),
                ('max_agenda_events', models.PositiveIntegerField(default=10, verbose_name='Máximo de Eventos')),
                ('price_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço Mensal')),
                ('price_quarterly', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço Trimestral')),
                ('price_semester', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço Semestral')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('features', models.ManyToManyField(blank=True, to='accounts.feature', verbose_name='Funcionalidades')),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
                'db_table': 'plans',
                'ordering': ['price_monthly'],
            },
        ),
        migrations.AddField(
            model_name='account',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='accounts.plan', verbose_name='Plano'),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('trial', 'Trial'), ('expired', 'Expirado'), ('overdue', 'Atrasado'), ('cancelled', 'Cancelado')], default='trial', max_length=20, verbose_name='Status')),
                ('billing_period', models.CharField(choices=[('monthly', 'Mensal'), ('quarterly', 'Trimestral'), ('semester', 'Semestral')], default='monthly', max_length=20, verbose_name='Período')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor')),
                ('start_date', models.DateField(verbose_name='Início')),
                ('end_date', models.DateField(verbose_name='Fim')),
                ('next_billing_date', models.DateField(blank=True, null=True, verbose_name='Próxima Cobrança')),
                ('payment_status', models.CharField(blank=True, max_length=20, verbose_name='Status do Pagamento')),
                ('last_payment_date', models.DateField(blank=True, null=True, verbose_name='Último Pagamento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='accounts.account', verbose_name='Conta')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.plan', verbose_name='Plano')),
            ],
            options={
                'verbose_name': 'Assinatura',
                'verbose_name_plural': 'Assinaturas',
                'db_table': 'subscriptions',
            },
        ),
    ]
