# Generated by Django 5.2.12 on 2026-04-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='highlight',
            field=models.BooleanField(default=False, verbose_name='Destaque (Recomendado)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Visível no Site'),
        ),
        migrations.AddField(
            model_name='plan',
            name='payment_link',
            field=models.URLField(blank=True, verbose_name='Link de Pagamento'),
        ),
        migrations.AddField(
            model_name='plan',
            name='short_description',
            field=models.CharField(blank=True, max_length=200, verbose_name='Descrição Curta'),
        ),
    ]
