# Generated by Django 5.2.12 on 2026-04-07 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('diretor_evento', 'Diretor de Evento / Event Manager'), ('produtor_executivo', 'Produtor Executivo'), ('coordenador_geral', 'Coordenador Geral'), ('gerente_projeto', 'Gerente de Projeto'), ('assistente_producao', 'Assistente de Produção'), ('diretor_tecnico', 'Diretor Técnico'), ('coordenador_tecnico', 'Coordenador Técnico'), ('stage_manager', 'Stage Manager (gerente de palco)'), ('roadie', 'Roadie / Assistente de palco'), ('rigger', 'Rigger (montagem aérea)'), ('tecnico_montagem', 'Técnico de montagem'), ('diretor_fotografia', 'Diretor de Fotografia'), ('operador_camera', 'Operador de Câmera'), ('tecnico_video', 'Técnico de Vídeo'), ('operador_switcher', 'Operador de Switcher'), ('tecnico_streaming', 'Técnico de Streaming / Live'), ('tecnico_led', 'Técnico de LED / Painel de LED'), ('editor_video', 'Editor de Vídeo'), ('tecnico_projecao', 'Técnico de Projeção'), ('tecnico_som', 'Técnico de Som (PA)'), ('operador_mesa_audio', 'Operador de Mesa de Áudio'), ('tecnico_monitor', 'Técnico de Monitor'), ('microfonista', 'Microfonista'), ('engenheiro_audio', 'Engenheiro de Áudio'), ('lighting_designer', 'Lighting Designer'), ('tecnico_iluminacao', 'Técnico de Iluminação'), ('operador_mesa_luz', 'Operador de Mesa de Luz'), ('programador_luz', 'Programador de luz'), ('cenografo', 'Cenógrafo'), ('montador_estrutura', 'Montadores de estrutura'), ('carpinteiro', 'Carpinteiros / Serralheiros'), ('tecnico_stands', 'Técnico de Stands (feiras)'), ('recepcionista', 'Recepcionistas'), ('credenciamento', 'Credenciamento'), ('hostess', 'Hostess / Promotores'), ('staff_apoio', 'Staff de apoio'), ('brigadista', 'Brigadistas'), ('seguranca', 'Segurança'), ('coordenador_marketing', 'Coordenador de Marketing'), ('social_media', 'Social Media'), ('fotografo', 'Fotógrafo'), ('assessoria_imprensa', 'Assessoria de Imprensa'), ('designer', 'Designer'), ('catering', 'Catering / Buffet'), ('garcom_bartender', 'Garçons / Bartenders'), ('limpeza', 'Limpeza'), ('transporte', 'Transporte'), ('motorista', 'Motoristas'), ('executivo_comercial', 'Executivo Comercial'), ('atendimento_cliente', 'Atendimento ao Cliente'), ('captacao_patrocinio', 'Captação de Patrocínio'), ('relacionamento_expositores', 'Relacionamento com Expositores'), ('tecnico_seguranca_trabalho', 'Técnico de Segurança do Trabalho'), ('bombeiro_civil', 'Bombeiro Civil'), ('responsavel_tecnico', 'Responsável Técnico'), ('equipe_medica', 'Equipe médica / ambulância'), ('convidado', 'Convidado')], max_length=50, verbose_name='Função/Cargo'),
        ),
    ]
