# Generated by Django 5.2.12 on 2026-04-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='notify_on_client_created',
            field=models.BooleanField(default=True, verbose_name='Notificar ao criar cliente'),
        ),
        migrations.AddField(
            model_name='account',
            name='notify_on_expense_created',
            field=models.BooleanField(default=True, verbose_name='Notificar ao criar despesa'),
        ),
        migrations.AddField(
            model_name='account',
            name='notify_on_job_created',
            field=models.BooleanField(default=True, verbose_name='Notificar ao criar trabalho'),
        ),
        migrations.AddField(
            model_name='account',
            name='notify_on_quote_created',
            field=models.BooleanField(default=True, verbose_name='Notificar ao criar orçamento'),
        ),
        migrations.AddField(
            model_name='account',
            name='notify_on_service_created',
            field=models.BooleanField(default=True, verbose_name='Notificar ao criar serviço'),
        ),
    ]
