# Generated by Django 5.2.13 on 2026-04-15 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_invite_token_user_invited_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='notify_on_job_confirmed',
            field=models.BooleanField(default=True, verbose_name='Notificar cliente ao confirmar trabalho'),
        ),
    ]
