# Generated by Django 5.2.13 on 2026-04-16 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_account_notify_on_job_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plan',
            field=models.ForeignKey(blank=True, help_text='Plano pessoal do usuário. Se não informado, usa o plano da empresa.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_with_plan', to='accounts.plan', verbose_name='Plano Individual'),
        ),
    ]
