# Generated by Django 5.2.13 on 2026-04-23 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_update_fcm_token_vapid'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fcmtoken',
            unique_together={('user', 'device_type')},
        ),
    ]
