# Generated by Django 5.2.13 on 2026-05-04 22:38

from django.db import migrations


def create_initial_privacy_term(apps, schema_editor):
    PrivacyTerm = apps.get_model('accounts', 'PrivacyTerm')
    if not PrivacyTerm.objects.filter(is_active=True).exists():
        PrivacyTerm.objects.create(
            version='1.0',
            content='Termo de Privacidade e Uso de Dados do 7event. Ao utilizar nossa plataforma, você concorda com a coleta e uso de suas informações conforme descrito neste termo. Para mais detalhes, entre em contato conosco.',
            is_active=True
        )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_fcmtoken_unique_together'),
    ]

    operations = [
        migrations.RunPython(create_initial_privacy_term, migrations.RunPython.noop),
    ]
