# Generated by Django 5.2.13 on 2026-04-23 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_fcmtoken_unique_together'),
        ('clients', '0005_remove_client_account'),
        ('expenses', '0003_remove_expense_account_remove_expense_user_and_more'),
        ('jobs', '0008_rename_user_job_created_by_remove_job_account_and_more'),
        ('quote', '0005_remove_quote_account'),
        ('services', '0002_remove_service_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='account',
        ),
        migrations.RemoveField(
            model_name='user',
            name='account',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_account_admin',
        ),
        migrations.AddField(
            model_name='plan',
            name='can_associate_professionals',
            field=models.BooleanField(default=False, verbose_name='Pode Associar Profissionais'),
        ),
        migrations.AddField(
            model_name='plan',
            name='job_creation_limit',
            field=models.PositiveIntegerField(default=-1, verbose_name='Limite de Criação de Jobs (-1 = ilimitado)'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='user',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, verbose_name='CNPJ'),
        ),
        migrations.AddField(
            model_name='user',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='users/logos/', verbose_name='Logo da Empresa'),
        ),
        migrations.AddField(
            model_name='user',
            name='legal_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nome Fantasia / Razão Social'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fim'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Início'),
        ),
        migrations.AlterField(
            model_name='user',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_with_plan', to='accounts.plan', verbose_name='Plano'),
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
