# Generated by Django 5.2.13 on 2026-04-24 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_subscription_account_remove_user_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='job_creation_limit',
            field=models.IntegerField(default=-1, verbose_name='Limite de Criação de Jobs (-1 = ilimitado)'),
        ),
    ]
