# Generated by Django 5.2.13 on 2026-05-01 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_plan_job_creation_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20, unique=True, verbose_name='Versão')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('is_active', models.BooleanField(default=False, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Termo de Privacidade',
                'verbose_name_plural': 'Termos de Privacidade',
                'db_table': 'privacy_terms',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Biografia'),
        ),
        migrations.AddField(
            model_name='user',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nome Completo'),
        ),
        migrations.AddField(
            model_name='user',
            name='portfolio_url',
            field=models.URLField(blank=True, verbose_name='URL do Portfólio'),
        ),
        migrations.AddField(
            model_name='user',
            name='rg',
            field=models.CharField(blank=True, max_length=20, verbose_name='RG'),
        ),
        migrations.AddField(
            model_name='user',
            name='show_sensitive_data',
            field=models.BooleanField(default=False, verbose_name='Permitir visualização de dados sensíveis'),
        ),
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.CharField(blank=True, max_length=500, verbose_name='Habilidades'),
        ),
        migrations.AddField(
            model_name='user',
            name='accepted_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_accepted', to='accounts.privacyterm', verbose_name='Termo aceito'),
        ),
    ]
