# Generated by Django 5.2.13 on 2026-05-03 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_add_privacy_terms_and_professional_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título da Tarefa')),
                ('date', models.DateField(verbose_name='Data')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Horário')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Concluída')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Tarefa Pessoal',
                'verbose_name_plural': 'Tarefas Pessoais',
                'db_table': 'personal_tasks',
                'ordering': ['date', 'time'],
                'indexes': [models.Index(fields=['user', 'date'], name='personal_ta_user_id_6b6834_idx'), models.Index(fields=['user', 'is_completed'], name='personal_ta_user_id_99454d_idx')],
            },
        ),
    ]
