# Generated by Django 5.2.13 on 2026-05-06 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_add_personal_task_model'),
        ('accounts', '0023_add_user_pix_key'),
    ]

    operations = [
    ]
