# Generated by Django 5.2.13 on 2026-05-06 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_add_personal_agenda_event_model'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='personalagendaevent',
            new_name='personal_ag_user_id_7b1d73_idx',
            old_name='personal_age_user_id_89dd1d_idx',
        ),
        migrations.RenameIndex(
            model_name='personalagendaevent',
            new_name='personal_ag_user_id_f782a3_idx',
            old_name='personal_age_user_id_63d8f2_idx',
        ),
        migrations.AlterField(
            model_name='plan',
            name='type',
            field=models.CharField(choices=[('free', 'Basic'), ('pro', 'Profissional'), ('business', 'Business')], max_length=20, unique=True, verbose_name='Tipo'),
        ),
    ]
