# Generated by Django 5.2.14 on 2026-06-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_stripe_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Ativo'), ('pending', 'Pendente'), ('trial', 'Trial'), ('expired', 'Expirado'), ('overdue', 'Atrasado'), ('cancelled', 'Cancelado')], default='trial', max_length=20, verbose_name='Status'),
        ),
    ]
