# Generated by Django 5.2.13 on 2026-06-04 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_remove_expense_account_remove_expense_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('equipment', 'Equipamento'), ('transport', 'Transporte'), ('food', 'Alimentação'), ('accommodation', 'Hospedagem'), ('equipe', 'Equipe'), ('fee', 'Taxa/Imposto'), ('other', 'Outro')], default='other', max_length=20, verbose_name='Categoria'),
        ),
    ]
