# Generated by Django 5.2.12 on 2026-04-03 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Serviço')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('estimated_duration_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Duração Estimada (horas)')),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor da Hora (R$)')),
                ('typical_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Despesas Típicas (R$)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='accounts.account', verbose_name='Conta')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'db_table': 'services',
                'ordering': ['name'],
            },
        ),
    ]
