# Generated by Django 5.2.12 on 2026-04-03 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('clients', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título do Orçamento')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Hora')),
                ('work_hours', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Horas de Trabalho')),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Custo de Mão de Obra')),
                ('expenses_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Custo de Despesas')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Enviado ao Cliente')),
                ('is_accepted', models.BooleanField(default=False, verbose_name='Aceito pelo Cliente')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='accounts.account', verbose_name='Conta')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='clients.client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Orçamento',
                'verbose_name_plural': 'Orçamentos',
                'db_table': 'quotes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Descrição')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Quantidade')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Unitário')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='quote.quote', verbose_name='Orçamento')),
            ],
            options={
                'verbose_name': 'Despesa do Orçamento',
                'verbose_name_plural': 'Despesas do Orçamento',
                'db_table': 'quote_expenses',
            },
        ),
        migrations.CreateModel(
            name='QuoteService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('custom_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço Customizado')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='quote.quote', verbose_name='Orçamento')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_services', to='services.service', verbose_name='Serviço')),
            ],
            options={
                'verbose_name': 'Serviço do Orçamento',
                'verbose_name_plural': 'Serviços do Orçamento',
                'db_table': 'quote_services',
            },
        ),
    ]
