# Generated by Django 5.2.12 on 2026-04-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='is_accepted',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='is_sent',
        ),
        migrations.AddField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('sent', 'Enviado'), ('negotiation', 'Em Negociação'), ('accepted', 'Aceito'), ('rejected', 'Recusado'), ('cancelled', 'Cancelado')], default='draft', max_length=20, verbose_name='Status'),
        ),
    ]
