# Generated by Django 5.2.13 on 2026-04-16 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0002_add_status_field'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuoteService',
        ),
    ]
