# Generated by Django 5.2.13 on 2026-04-23 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0004_quote_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='account',
        ),
    ]
