# Generated by Django 5.2.12 on 2026-04-03 03:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('event_type', models.CharField(choices=[('wedding', 'Casamento'), ('debutante', 'Festa de 15 anos'), ('corporate', 'Corporativo'), ('birthday', 'Aniversário'), ('concert', 'Show/Concerto'), ('graduation', 'Formatura'), ('baptism', 'Batizado'), ('other', 'Outro')], default='other', max_length=20, verbose_name='Tipo de Evento')),
                ('start_date', models.DateField(verbose_name='Data do Evento')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data Final')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Hora Inicial')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Hora Final')),
                ('location', models.CharField(blank=True, max_length=300, verbose_name='Local')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('cache', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cachê')),
                ('payment_type', models.CharField(choices=[('advance', 'Pagamento Antecipado'), ('full', 'Pagamento Total'), ('partial', 'Pagamento Parcial')], default='full', max_length=20, verbose_name='Tipo de Pagamento')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('payment_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Total')),
                ('payment_partial_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Parcial')),
                ('payment_partial_date', models.DateField(blank=True, null=True, verbose_name='Data Pagamento Parcial')),
                ('payment_remaining_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Restante')),
                ('payment_remaining_date', models.DateField(blank=True, null=True, verbose_name='Data Pagamento Restante')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Confirmado'), ('completed', 'Concluído'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Status do Evento')),
                ('payment_status', models.CharField(choices=[('pending', 'Pendente'), ('partial', 'Parcial'), ('paid', 'Pago')], default='pending', max_length=20, verbose_name='Status de Pagamento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='accounts.account', verbose_name='Conta')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='clients.client', verbose_name='Cliente')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Trabalho',
                'verbose_name_plural': 'Trabalhos',
                'db_table': 'jobs',
                'ordering': ['-start_date'],
            },
        ),
    ]
