# Generated by Django 5.2.12 on 2026-04-07 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='event_type',
            field=models.CharField(choices=[('corporativo', 'Corporativo'), ('feiras_exposicoes', 'Feiras e Exposições'), ('shows_festivais', 'Shows e Festivais'), ('teatro', 'Teatro'), ('gravacao_dvd', 'Gravação de DVD'), ('podcasts', 'Podcasts'), ('producao_conteudo', 'Produção de Conteúdo'), ('eventos', 'Eventos'), ('eventos_sociais', 'Eventos Sociais'), ('internet', 'Internet'), ('lives', 'Lives / Transmissões ao Vivo'), ('coletivas_imprensa', 'Coletivas de Imprensa'), ('programas_tv', 'Programas de Televisão / Reality'), ('documentarios', 'Documentários'), ('campanha_publicitaria', 'Campanha Publicitária')], default='corporativo', max_length=30, verbose_name='Tipo de Serviço'),
        ),
    ]
