# Generated by Django 5.2.13 on 2026-04-18 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_approved_at_job_approved_by_job_workers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='workers',
        ),
    ]
