# Generated by Django 5.2.13 on 2026-04-21 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_remove_workers_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='payment_confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Confirmação Pagamento'),
        ),
        migrations.AddField(
            model_name='job',
            name='payment_partial_confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Confirmação 1ª Parcela'),
        ),
        migrations.AddField(
            model_name='job',
            name='payment_remaining_confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Confirmação 2ª Parcela'),
        ),
    ]
