# Generated by Django 5.2.13 on 2026-04-23 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_job_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='user',
            new_name='created_by',
        ),
        migrations.RemoveField(
            model_name='job',
            name='account',
        ),
        migrations.AddField(
            model_name='job',
            name='total_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Orçamento Total (Valor Bruto)'),
        ),
        migrations.CreateModel(
            name='JobStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor do Cachê')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('accepted', 'Aceito'), ('rejected', 'Recusado')], default='pending', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_staff', to='jobs.job', verbose_name='Trabalho')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Profissional')),
            ],
            options={
                'verbose_name': 'Equipe do Trabalho',
                'verbose_name_plural': 'Equipes dos Trabalhos',
                'db_table': 'jobs_jobstaff',
                'ordering': ['-created_at'],
                'unique_together': {('job', 'professional')},
            },
        ),
    ]
