# Generated by Django 5.2.13 on 2026-04-29 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_add_role_to_jobstaff'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobstaff',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('advance', 'Pagamento Antecipado'), ('full', 'Pagamento Total'), ('partial', 'Pagamento Parcial')], max_length=20, verbose_name='Tipo de Pagamento (Contrato Individual)'),
        ),
        migrations.AlterField(
            model_name='jobstaff',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('accepted', 'Aceito'), ('confirmed', 'Confirmado'), ('rejected', 'Recusado'), ('cancelled_by_prof', 'Cancelado pelo Profissional')], default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
