# Generated by Django 5.2.13 on 2026-04-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_add_confirmed_status_and_payment_type_to_jobstaff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobstaff',
            name='status',
            field=models.CharField(choices=[('pending', 'pendente'), ('accepted', 'Aceito'), ('confirmed', 'Confirmado'), ('rejected', 'Recusado'), ('cancelled_by_prof', 'Cancelado pelo Profissional'), ('paid', 'Pago')], default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
