# Generated by Django 5.2.13 on 2026-04-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_add_paid_status_to_jobstaff'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='has_technical_visit',
            field=models.BooleanField(default=False, verbose_name='Possui Visita Técnica'),
        ),
        migrations.AddField(
            model_name='job',
            name='technical_visit_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Visita Técnica'),
        ),
        migrations.AddField(
            model_name='job',
            name='technical_visit_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário da Visita Técnica'),
        ),
    ]
