# Generated by Django 5.2.14 on 2026-06-29 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        # RenameIndex removidos -- os nomes dos indices diferem entre ambientes
        # e essas operacoes sao apenas cosmeticas (normalizacao de nomes).
    ]
