# Generated by Django 5.2.14 on 2026-06-29 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='paymenttransaction',
            new_name='payment_tra_billing_665db1_idx',
            old_name='payment_tran_billing_4fcf61_idx',
        ),
        migrations.RenameIndex(
            model_name='paymenttransaction',
            new_name='payment_tra_provide_4c2167_idx',
            old_name='payment_tran_provider_3a2163_idx',
        ),
    ]
