# Generated by Django 5.2.14 on 2026-07-03 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_rename_payment_tran_billing_4fcf61_idx_payment_tra_billing_665db1_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='external_reference',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
